---
title: "Interdashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(tidyverse)
library(viridis)
library(plotly)
library(p8105.datasets)
library(flexdashboard)
```

Column {data-width=650}
-----------------------------------------------------------------------

### Chart A
This is the violin chart shows the distribution of grade of korean restaurant in Manhattan area
```{r}
data("rest_inspec")

korean_restaurant_violin=rest_inspec%>%
   filter(str_detect(cuisine_description, "[Kk][Oo][Rr][Ee][Aa][Nn]"),
         boro %in% c("MANHATTAN"))%>% 
  mutate(grade = fct_relevel(as.character(grade))) %>% 
  plot_ly(x = ~grade, y = ~score, type ="violin", color=~grade, alpha=0.5)
  

 korean_restaurant_violin 
```

Column {data-width=350}
-----------------------------------------------------------------------

### Chart B

This is the scatterplot shows the mean score for korean restaurant by street, helping us to find the best street to explore korean food!

```{r}

 korean_restaurant=rest_inspec%>%
  filter(str_detect(cuisine_description, "[Kk][Oo][Rr][Ee][Aa][Nn]"),
         boro %in% c("MANHATTAN"))%>% 
  group_by(street) %>% 
  summarise(mean_score = mean(score)) %>% 
  drop_na()%>%
   mutate(street = fct_reorder(street, mean_score)) %>% 
  plot_ly(
    x = ~street, y = ~mean_score, color = ~street, type = "scatter") 

korean_restaurant

```

### Chart C
This is the bar chart showing the grade for Manhattan cafe, good to see A level is the highest proportion level!
```{r}
manhattan_cafe=
rest_inspec %>% 
  filter(str_detect(dba, "[Cc][Aa][Ff][Ee]"),
         boro %in% c("MANHATTAN")) %>%
  group_by(grade)%>%
  summarize(n = n()) %>% 
  drop_na()%>%
  spread(key = grade, value = n)%>%
  pivot_longer(
    A:Z,
    names_to = "grade",
    values_to = "number"
  )%>%
  mutate(grade= fct_reorder(grade, number))%>%
  plot_ly(
    x=~grade, y= ~ number, color= ~ grade, type="bar"
  )

manhattan_cafe

```